"""initial schema

Revision ID: 6243728f33d1
Revises: 
Create Date: 2026-09-09 07:42:51.020711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6243728f33d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('rss_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=1024), nullable=True),
    sa.Column('feed_type', sa.String(length=50), nullable=True),
    sa.Column('podcast_guid', sa.String(length=255), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('feed_id')
    )
    op.create_index(op.f('ix_feeds_rss_url'), 'feeds', ['rss_url'], unique=True)
    op.create_table('tags',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name', 'category', name='uq_tag_name_category')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('task_logs',
    sa.Column('task_log_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_log_id')
    )
    op.create_index(op.f('ix_task_logs_status'), 'task_logs', ['status'], unique=False)
    op.create_index(op.f('ix_task_logs_task_type'), 'task_logs', ['task_type'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('curated_playlists',
    sa.Column('playlist_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id')
    )
    op.create_index(op.f('ix_curated_playlists_user_id'), 'curated_playlists', ['user_id'], unique=False)
    op.create_table('episodes',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('guid', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('audio_url', sa.String(length=1024), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_url', sa.String(length=1024), nullable=True),
    sa.Column('chapters_url', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('episode_type', sa.String(length=50), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.feed_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id'),
    sa.UniqueConstraint('feed_id', 'guid', name='uq_episode_feed_guid')
    )
    op.create_index(op.f('ix_episodes_feed_id'), 'episodes', ['feed_id'], unique=False)
    op.create_index(op.f('ix_episodes_guid'), 'episodes', ['guid'], unique=False)
    op.create_index(op.f('ix_episodes_published_at'), 'episodes', ['published_at'], unique=False)
    op.create_table('episode_tags',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'tag_id')
    )
    op.create_table('insights',
    sa.Column('insight_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('insight_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_index(op.f('ix_insights_episode_id'), 'insights', ['episode_id'], unique=False)
    op.create_table('playlist_episodes',
    sa.Column('playlist_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['curated_playlists.playlist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'episode_id')
    )
    op.create_table('user_episode_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('position_seconds', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'episode_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_episode_progress')
    op.drop_table('playlist_episodes')
    op.drop_index(op.f('ix_insights_episode_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_table('episode_tags')
    op.drop_index(op.f('ix_episodes_published_at'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_guid'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_feed_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_curated_playlists_user_id'), table_name='curated_playlists')
    op.drop_table('curated_playlists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_logs_task_type'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_status'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_feeds_rss_url'), table_name='feeds')
    op.drop_table('feeds')
    # ### end Alembic commands ###
